[package]
name = "rust-async"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jeresoftx/rust-async"
description = "Programación asíncrona en Rust para Jeresoft Academy."
readme = "README.md"

[lib]
name = "rust_async"
path = "src/lib.rs"

[dependencies]
